<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container97BKcbs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container97BKcbs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container97BKcbs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container97BKcbs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container97BKcbs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '97BKcbs',
    'container.build_id' => 'a2718626',
    'container.build_time' => 1615824440,
], __DIR__.\DIRECTORY_SEPARATOR.'Container97BKcbs');
