<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'newclient' => [[], ['_controller' => 'App\\Controller\\ClientController::new'], [], [['text', '/client/new']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\FacetagramController::home'], [], [['text', '/']], [], []],
    'a_propos' => [[], ['_controller' => 'App\\Controller\\FacetagramController::about'], [], [['text', '/about']], [], []],
    'produit' => [[], ['_controller' => 'App\\Controller\\FacetagramController::product'], [], [['text', '/product']], [], []],
    'service' => [[], ['_controller' => 'App\\Controller\\FacetagramController::service'], [], [['text', '/service']], [], []],
    'contactlist' => [[], ['_controller' => 'App\\Controller\\FormController::show'], [], [['text', '/contactlist']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\FormController::new'], [], [['text', '/contact']], [], []],
    'app_form_edit' => [['id'], ['_controller' => 'App\\Controller\\FormController::edit'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id'], ['text', '/contact/edit']], [], []],
    'app_form_delete' => [['id'], ['_controller' => 'App\\Controller\\FormController::delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id'], ['text', '/contact/delete']], [], []],
    'newproduct' => [[], ['_controller' => 'App\\Controller\\ProductController::new'], [], [['text', '/product/new']], [], []],
    'security_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'security_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'app_facetagram' => [[], ['_controller' => 'App\\Controller\\FacetagramController::home'], [], [['text', '/home']], [], []],
];
